# Generated by Django 2.2 on 2019-04-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipbump', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='SiteConfiguration',
        ),
        migrations.RenameModel(
            old_name='StoreSettings',
            new_name='Store',
        ),
    ]
