# Generated by Django 2.2 on 2019-04-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipbump', '0002_auto_20190421_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Location',
        ),
    ]
